### ISSUE TITLE
Explain how to run tests locally

### ISSUE THREAD

**Issue by lastmjs** [ethereum-alarm-clock/timenode-core#265]
I'm trying to get the tests to pass on a fresh clone, but I don't think I'm going to have much luck: https://github.com/ethereum-alarm-clock/timenode-core/pull/239#issuecomment-416603186

The steps here should be documented clearly for contributors to be able to run tests locally.

**Comment by lastmjs** [comment]
In fact, I think everything should be included directly in this repo, so that once you do an `npm install`, `npm run test` will whip up whatever ganache or other things that are necessary for the tests to run successfully.

**Comment by kosecki123** [comment]
Indeed the instruction on README were missing.

Fixed https://github.com/ethereum-alarm-clock/timenode-core/commit/f744f73a10bbc29fc7dae664c4005840d3e92962
